import {
  ArrowRight,
  BarChart3,
  Bell,
  CheckCircle2,
  CircleHelp,
  CreditCard,
  Dumbbell,
  ExternalLink,
  Eye,
  FolderOpen,
  GraduationCap,
  LayoutDashboard,
  LifeBuoy,
  Mail,
  MapPin,
  MoonStar,
  Network,
  Phone,
  Quote,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Sun,
  UserCheck,
  Users,
  XCircle,
} from 'lucide-react';

const iconMap = {
  analytics: BarChart3,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  call: Phone,
  cancel: XCircle,
  check_circle: CheckCircle2,
  contrast: MoonStar,
  dashboard: LayoutDashboard,
  dashboard_customize: LayoutDashboard,
  folder_open: FolderOpen,
  format_quote: Quote,
  group: Users,
  help: CircleHelp,
  help_center: LifeBuoy,
  how_to_reg: UserCheck,
  hub: Network,
  light_mode: Sun,
  location_on: MapPin,
  mail: Mail,
  monitoring: BarChart3,
  notifications: Bell,
  open_in_new: ExternalLink,
  payments: CreditCard,
  rocket_launch: Rocket,
  school: GraduationCap,
  search: Search,
  security: ShieldCheck,
  settings: Settings,
  sports_kabaddi: Dumbbell,
  visibility: Eye,
};

export default function AppIcon({ name, className, strokeWidth = 2, ...props }) {
  const Icon = iconMap[name] ?? CircleHelp;

  return <Icon aria-hidden="true" className={className} strokeWidth={strokeWidth} {...props} />;
}
