import {
  AlertCircle,
  CalendarCheck2,
  CalendarDays,
  ArrowRight,
  BarChart3,
  Bell,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  CreditCard,
  Download,
  Dumbbell,
  Edit,
  EllipsisVertical,
  ExternalLink,
  FileText,
  Globe,
  Headset,
  Eye,
  Filter,
  FolderOpen,
  GraduationCap,
  LayoutDashboard,
  LifeBuoy,
  LogOut,
  Mail,
  MapPin,
  MoonStar,
  Network,
  Phone,
  Plus,
  Quote,
  RefreshCw,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  SortAsc,
  Sparkles,
  SquareActivity,
  Star,
  Sun,
  TrendingUp,
  Upload,
  UserRound,
  UserCheck,
  Users,
  Wallet,
  XCircle,
  X,
  Diamond,
  BarChart,
  Check,
  Trash2,
  Code,
  Send,
  Car,
  Calendar,
  Video,
  Map,
  Home,
  Menu,
  ChevronUp,
  Clock,
  MessageSquare,
  Building2,
  MapPinned,
  Navigation,
  Route,
} from 'lucide-react';

const iconMap = {
  add: Plus,
  activity: SquareActivity,
  analytics: BarChart3,
  calendar_today: CalendarDays,
  arrow_forward: ArrowRight,
  date_range: CalendarDays,
  download: Download,
  auto_awesome: Sparkles,
  event_available: CalendarCheck2,
  call: Phone,
  cancel: XCircle,
  check_circle: CheckCircle2,
  contrast: MoonStar,
  dashboard: LayoutDashboard,
  dashboard_customize: LayoutDashboard,
  description: FileText,
  edit: Edit,
  filter_list: Filter,
  folder_open: FolderOpen,
  format_quote: Quote,
  group: Users,
  groups: Users,
  help: CircleHelp,
  help_center: LifeBuoy,
  how_to_reg: UserCheck,
  hub: Network,
  light_mode: Sun,
  language: Globe,
  location_on: MapPin,
  logout: LogOut,
  mail: Mail,
  more_vert: EllipsisVertical,
  monitoring: BarChart3,
  notifications: Bell,
  open_in_new: ExternalLink,
  person_pin: UserRound,
  payments: CreditCard,
  refresh: RefreshCw,
  rocket_launch: Rocket,
  school: GraduationCap,
  search: Search,
  security: ShieldCheck,
  settings: Settings,
  sort: SortAsc,
  sports_kabaddi: Dumbbell,
  star: Star,
  support: Headset,
  support_agent: Headset,
  task_alt: CheckCircle2,
  today: CalendarDays,
  trending_up: TrendingUp,
  upload: Upload,
  verified_user: UserCheck,
  visibility: Eye,
  warning: AlertCircle,
  account_balance_wallet: Wallet,
  bar_chart_3: BarChart3,
  bar_chart: BarChart,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  check: Check,
  check_circle: CheckCircle2,
  delete: Trash2,
  diamond: Diamond,
  code: Code,
  send: Send,
  directions_car: Car,
  schedule: Calendar,
  video_call: Video,
  video: Video,
  map: Map,
  home: Home,
  menu: Menu,
  close: X,
  clock: Clock,
  message: MessageSquare,
  building: Building2,
  map_pinned: MapPinned,
  navigation: Navigation,
  route: Route,
};

export default function AppIcon({ name, className, strokeWidth = 2, ...props }) {
  const Icon = iconMap[name] ?? CircleHelp;

  return <Icon aria-hidden="true" className={className} strokeWidth={strokeWidth} {...props} />;
}
